import { Entry } from "../src/saveoffline";

export const config: Entry[] = [
    "https://www.reddit.com/r/HFY/wiki/series/first_contact_ralts_bloodthorne",
    "https://www.reddit.com/r/HFY/wiki/series/retreat_hell",
    "https://www.reddit.com/r/HFY/wiki/series/when_the_gods_come_to_visit",
    "https://www.reddit.com/r/HFY/wiki/series/new_students",
    "https://www.reddit.com/r/hfy/wiki/series/an_unstoppable_machine",
    "https://www.reddit.com/r/HFY/wiki/series/because_someone_had_to",
    "https://www.reddit.com/r/HFY/wiki/series/solaria_rising",
    "https://www.reddit.com/r/HFY/wiki/series/dark",
    "https://www.reddit.com/r/hfy/wiki/series/chrysalis",
    "https://www.reddit.com/r/hfy/wiki/series/first_contact_protocols",
    "https://www.reddit.com/r/hfy/wiki/series/when_deathworlders_meet",
    "https://www.reddit.com/r/hfy/wiki/series/very_clever_primitives",
    {
        type: "series",
        title: "Fubsyverse",
        author: "ReallyNotMichaelsMom",
        entries: [
            "https://www.reddit.com/r/hfy/wiki/series/the_care_and_feeding_of_humans",
            "https://www.reddit.com/r/hfy/wiki/series/all_about_limniads",
            "https://www.reddit.com/r/HFY/wiki/series/some_of_my_best_friends_are_human",
        ],
    },
    "https://www.reddit.com/r/HFY/wiki/series/three_fleets",
    "https://www.reddit.com/r/HFY/wiki/series/lost_boys",
    "https://www.reddit.com/r/hfy/wiki/series/humans_are_weird",
    "https://www.reddit.com/r/hfy/wiki/series/uplift_protocol",
    "https://www.reddit.com/r/HFY/wiki/series/elven_paranormal_containment_foundation",
    "https://www.reddit.com/r/HFY/wiki/series/of_men_and_dragons",
    {
        type: "authorfilter",
        author: "Hydrael",
        username: "Hydrael",
        subreddit: "redditserials",
        titlesearch: "A Staff of Crystal and Bone",
        title: "A Staff of Crystal and Bone",
        stop: "[A Staff of Crystal and Bone] Part 1",
    },
    {
        type: "tocpost",
        post:
            "https://www.reddit.com/r/redditserials/comments/da9uwe/the_dragons_apprentice_index/",
        title: "The Dragon's Apprentice",
    },
    {
        type: "authorfilter",
        author: "Earthfall10",
        username: "Earthfall10",
        subreddit: "HFY",
        titlesearch: "Humans are ",
        title: "Humans are ",
        stop: "Humans are ",
    },
    {
        type: "authorfilter",
        author: "Mackelsaur",
        username: "Mackelsaur",
        subreddit: "HFY",
        titlesearch: "Reverse Engineering",
        title: "Reverse Engineering",
        stop: "Reverse Engineering - Part 1",
    },
    {
        type: "authorfilter",
        author: "AngryaboutVideogames",
        username: "AngryaboutVideogames",
        subreddit: "HFY",
        titlesearch: "Frozen Homes",
        title: "Frozen Homes",
        stop: "Frozen Homes",
    },
    {
        // there is a toc page but it has too many
        // links and hasn't been updated recently
        type: "authorfilter",
        author: "UpIsOben",
        username: "UpIsOben",
        subreddit: "HFY",
        titlesearch: "We intend no harm",
        title: "We intend no harm",
        stop: "[OC] We intend no harm - Chapter 1 (Visitors)",
    },
    {
        type: "set",
        title: "Short Stories",
        author: "Various Authors",
        posts: [
            "https://www.reddit.com/r/HFY/comments/a50nnp/a_clerical_error.json",
            "https://www.reddit.com/r/HFY/comments/8a43i1/fuck_it.json",
            "https://www.reddit.com/r/HFY/comments/abqcz7/oc_just_one_ship.json",
            "https://www.reddit.com/r/HFY/comments/bdbi04/we_knew_them.json",
            "https://www.reddit.com/r/HFY/comments/c9g2md/melody_of_the_heart.json",
            "https://www.reddit.com/r/HFY/comments/aw600n/humanitys_price.json",
            "https://www.reddit.com/r/HFY/comments/631sm0/lablonnamedadon.json",
            "https://www.reddit.com/r/HFY/comments/8ewhna/terran_tears.json",
            "https://www.reddit.com/r/HFY/comments/b1omqd/human_tech.json",
            "https://www.reddit.com/r/HFY/comments/b901nm/humans_train_them_young.json",
            "https://www.reddit.com/r/HFY/comments/bvz0et/sleep_on_it.json",
            "https://www.reddit.com/r/HFY/comments/89f3u0/human_training.json",
            "https://www.reddit.com/r/HFY/comments/avid1g/none_remain.json",
            "https://www.reddit.com/r/HFY/comments/axfewg/you_ate_what.json",
            "https://www.reddit.com/r/HFY/comments/8d65as/oc_rules.json",
            "https://www.reddit.com/r/HFY/comments/6ide7r/oc_mistakes_were_never_made.json",
            "https://www.reddit.com/r/HFY/comments/7qaaif/oc_a_villain_a_thief.json",
            "https://www.reddit.com/r/HFY/comments/c5atuy/the_conversation.json",
            "https://www.reddit.com/r/HFY/comments/avb7wb/this_is_complete_nonsense.json",
            "https://www.reddit.com/r/HFY/comments/9o4328/told_ya_so.json",
            "https://www.reddit.com/r/HFY/comments/aekt1v/oc_i_am_the_internet.json",
            "https://www.reddit.com/r/HFY/comments/6lfc6n/the_first_human.json",
            "https://www.reddit.com/r/HFY/comments/8k89xk/why_humans_cant_have_nice_things.json",
            "https://www.reddit.com/r/HFY/comments/8l19qc/why_humans_cant_have_nice_things_ii.json",
            "https://www.reddit.com/r/HFY/comments/9jsuri/oc_humanity_said.json",
            "https://www.reddit.com/r/HFY/comments/8hjk2k/and_they_laughed.json",
            "https://www.reddit.com/r/HFY/comments/7egfzc/report_to_the_galactic_conference_concerning_the.json",
            "https://www.reddit.com/r/HFY/comments/a9q5tu/the_humans_are_coming.json",
            "https://www.reddit.com/r/HFY/comments/axbxyb/why_are_you_all_fearless.json",
            "https://www.reddit.com/r/HFY/comments/826m94/the_sound_of_distant_guns.json",
            "https://www.reddit.com/r/HFY/comments/aw4qxb/oc_crisis_simulation.json",
            "https://www.reddit.com/r/HFY/comments/blczvy/the_art_of_not_fighting_humans.json",
            "https://www.reddit.com/r/HFY/comments/89ssj1/human_training_methods_by_gornak.json",
            "https://www.reddit.com/r/HFY/comments/c7mz9b/i_work_at_nasa_we_made_alien_contact_yesterday.json",
            "https://www.reddit.com/r/HFY/comments/c8i2m5/i_work_at_nasa_we_made_alien_contact_last_week.json",
            "https://www.reddit.com/r/HFY/comments/bbqznz/multibrain.json",
            "https://www.reddit.com/r/HFY/comments/c95j4o/the_most_militarized_planet_in_the_universe.json",
            "https://www.reddit.com/r/HFY/comments/a7y9gk/just_give_us_a_reason_please.json",
            "https://www.reddit.com/r/HFY/comments/9zqrtc/ocextrapolation_error.json",
            "https://www.reddit.com/r/HFY/comments/6lmnny/oc_human_special_forces.json",
            "https://www.reddit.com/r/HFY/comments/9w9c89/good_neighbors.json",
            "https://www.reddit.com/r/HFY/comments/bltagf/the_full_wrath_of_terra.json",
            "https://www.reddit.com/r/HFY/comments/7i7yti/the_present_incursion.json",
            "https://www.reddit.com/r/HFY/comments/9e3cs2/oc_terran_for_terror.json",
            "https://www.reddit.com/r/HFY/comments/a3glq9/oc_the_last_human.json",
            "https://www.reddit.com/r/HFY/comments/bu5vje/tactical_observation.json",
            "https://www.reddit.com/r/HFY/comments/69z8d1/oc_terms_and_conditions_may_apply.json",
            "https://www.reddit.com/r/HFY/comments/cm9ni3/a_human_ordnance_technician_introduces_himself.json",
            "https://www.reddit.com/r/HFY/comments/5m4jdf/alien_minds.json",
            "https://www.reddit.com/r/HFY/comments/7eahzt/a_human_an_exotic_space_babe_and_a_genocidal.json",
            "https://www.reddit.com/r/HFY/comments/bwyk5n/human_historia.json",
            "https://www.reddit.com/r/HFY/comments/aa9nvj/the_hammer.json",
            "https://www.reddit.com/r/HFY/comments/88w63y/oc_joining_a_human_crew.json",
            "https://www.reddit.com/r/HFY/comments/8i4ri2/oc_a_package_deal.json",
            "https://www.reddit.com/r/HFY/comments/7uu0sd/the_human_horror.json",
            "https://www.reddit.com/r/HFY/comments/ammmk8/oc_death_song.json",
            "https://www.reddit.com/r/HFY/comments/bc1fxm/a_very_human_challenge.json",
            "https://www.reddit.com/r/HFY/comments/6zx87z/oc_traditional_earth_weapons.json",
            "https://www.reddit.com/r/HFY/comments/arobwa/oc_an_empty_universe.json",
            "https://www.reddit.com/r/HFY/comments/7pf24k/occhildren.json",
            "https://www.reddit.com/r/HFY/comments/906unw/only_human.json",
            "https://www.reddit.com/r/HFY/comments/brur4i/the_right_demon_for_the_job.json",
            "https://www.reddit.com/r/HFY/comments/6mcbh0/oc_ignore_the_tourists.json",
            "https://www.reddit.com/r/HFY/comments/cb65ym/oc_the_yeet_principle.json",
            "https://www.reddit.com/r/HFY/comments/5t26xs/humans_welcome.json",
            "https://www.reddit.com/r/HFY/comments/a2l4gc/exchange_program.json",
            "https://www.reddit.com/r/HFY/comments/699fhc/longevity.json",
            "https://www.reddit.com/r/HFY/comments/cmo3us/oc_i_love_my_human.json",
            "https://www.reddit.com/r/HFY/comments/c2a5to/you_shot_me.json",
            "https://www.reddit.com/r/HFY/comments/a04vrf/the_genie.json",
            "https://www.reddit.com/r/HFY/comments/8kdx4j/the_old_elvish_war.json",
            "https://www.reddit.com/r/HFY/comments/60h3d8/they_are_water.json",
            "https://www.reddit.com/r/HFY/comments/bpaxv1/mender.json",
            "https://www.reddit.com/r/HFY/comments/cs2j39/pi_earth_is_famous_for_its_ability_to_repel.json",
            "https://www.reddit.com/r/HFY/comments/besbpy/they_dont_understand.json",
            "https://www.reddit.com/r/HFY/comments/83yb1m/human_magic.json",
            "https://www.reddit.com/r/HFY/comments/4uutw2/and_man_said_fuck_you.json",
            "https://www.reddit.com/r/HFY/comments/7l8wkt/the_god_emperor.json",
            "https://www.reddit.com/r/HFY/comments/a0rit7/blind.json",
            "https://www.reddit.com/r/HFY/comments/782w7z/oc_the_reason_humans_scare_me.json",
            "https://www.reddit.com/r/HFY/comments/5prjh1/oc_how_diplomatic.json",
            "https://www.reddit.com/r/HFY/comments/ama2vu/exotic_pets.json",
            "https://www.reddit.com/r/HFY/comments/5zk80w/oc_the_price_of_consensus.json",
            "https://www.reddit.com/r/HFY/comments/6r5g1h/oc_how_to_break_a_human.json",
            "https://www.reddit.com/r/HFY/comments/auoeku/the_professor_will_take_questions_now.json",
            "https://www.reddit.com/r/HFY/comments/bmqdcn/mankind_has_fallen.json",
            "https://www.reddit.com/r/HFY/comments/cf1i5n/glass.json",
            "https://www.reddit.com/r/HFY/comments/crcna5/humans_innate_ability.json",
            "https://www.reddit.com/r/HFY/comments/bwnydq/these_games_we_play.json",
            "https://www.reddit.com/r/HFY/comments/bri1dl/oc_pocket_sand.json",
            "https://www.reddit.com/r/HFY/comments/783wwm/to_ally_with_humanity.json",
            "https://www.reddit.com/r/HFY/comments/bbapwt/we_do.json",
            "https://www.reddit.com/r/HFY/comments/ci9194/fix_bayonets.json",
            "https://www.reddit.com/r/HFY/comments/8y56yq/i_saw_a_human_once.json",
            "https://www.reddit.com/r/HFY/comments/clj8ac/island_in_the_stars.json",
            "https://www.reddit.com/r/HFY/comments/43ov2r/war.json",
            "https://www.reddit.com/r/HFY/comments/bdonkn/all_systems_science_university_so_what_youre.json",
            "https://www.reddit.com/r/HFY/comments/bosxuq/army_surplus.json",
            "https://www.reddit.com/r/HFY/comments/80nhm9/oc_the_horrifying_truth_about_humans.json",
            "https://www.reddit.com/r/HFY/comments/bx3ql6/when_the_gods_come_to_visit.json",
            "https://www.reddit.com/r/HFY/comments/c05idf/humans_are_weird_those_were_warnings_not.json",
            "https://www.reddit.com/r/HFY/comments/a32wbn/the_unfought_war.json",
            "https://www.reddit.com/r/HFY/comments/44zuvf/oc_nightwater.json",
            "https://www.reddit.com/r/HFY/comments/7t2tp6/oc_night.json",
            "https://www.reddit.com/r/HFY/comments/86b550/oc_humanity.json",
            "https://www.reddit.com/r/HFY/comments/9epbul/the_drunk.json",
            "https://www.reddit.com/r/HFY/comments/bnaaz1/slumbering_giants.json",
            "https://www.reddit.com/r/HFY/comments/b820nz/why_did_we_lose.json",
            "https://www.reddit.com/r/HFY/comments/cnvd5g/human_stories.json",
            "https://www.reddit.com/r/HFY/comments/9wvr9t/offspring.json",
            "https://www.reddit.com/r/HFY/comments/9p42v6/fourteen_beings_left_one_stayed_back.json",
            "https://www.reddit.com/r/HFY/comments/au6wa6/shot_at_dawn.json",
            "https://www.reddit.com/r/HFY/comments/c70b2d/luck.json",
            "https://www.reddit.com/r/HFY/comments/8cj5s3/oc_they_torture_themselves.json",
            "https://www.reddit.com/r/HFY/comments/btced9/the_mad_ones.json",
            "https://www.reddit.com/r/HFY/comments/6aqi61/empirecrasherexe_why_humans_should_never_have_an.json",
            "https://www.reddit.com/r/HFY/comments/amfuvt/spitting_fire.json",
            "https://www.reddit.com/r/HFY/comments/5qiclb/oc_the_ethics_officer.json",
            "https://www.reddit.com/r/HFY/comments/9q2426/yearly_xenowarfare_training.json",
            "https://www.reddit.com/r/HFY/comments/5k4gv8/we_were_mistaken.json",
            "https://www.reddit.com/r/HFY/comments/7wxhxu/oc_the_most_terrifying_sound_in_the_galaxy.json",
            "https://www.reddit.com/r/HFY/comments/bsp706/100000_a_drink.json",
            "https://www.reddit.com/r/HFY/comments/6jsejd/oc_new_rules_and_guidelines_from_hr_for_working.json",
            "https://www.reddit.com/r/HFY/comments/c61726/supernatural_help_wanted.json",
            "https://www.reddit.com/r/HFY/comments/aw0l5x/insurance.json",
            "https://www.reddit.com/r/HFY/comments/7is3mj/almost_peaceful.json",
            "https://www.reddit.com/r/HFY/comments/cqj3uw/oc_from_a_fking_boat.json",
            "https://www.reddit.com/r/HFY/comments/ckcsma/humans_are_defensive_in_nature.json",
            "https://www.reddit.com/r/HFY/comments/88k7rv/the_legend_of_jim.json",
            "https://www.reddit.com/r/HFY/comments/b6hjwf/a_rock.json",
            "https://www.reddit.com/r/HFY/comments/8xfcc8/human_combat_psychology_brotherhood.json",
            "https://www.reddit.com/r/HFY/comments/517k3r/they_are_all_warforms.json",
            "https://www.reddit.com/r/HFY/comments/bg6jas/percussive_maintenance.json",
            "https://www.reddit.com/r/HFY/comments/b6zfmv/the_court_case_of_the_pirates_vs_fred_oc.json",
            "https://www.reddit.com/r/HFY/comments/6mdxjg/oc_humans_are_the_galaxies_guard_dogs.json",
            "https://www.reddit.com/r/HFY/comments/c0ojkr/oc_abby514.json",
            "https://www.reddit.com/r/HFY/comments/6fy1o0/oc_rule_of_the_gricka.json",
        ],
    },
];
